remote_theme: pages-themes/architect@v0.2.0
title: Renee Bartos
description: Technical Operations & Customer Success Leader
google_analytics:
show_downloads: false
github:
  is_project: false
  repository_url: https://www.linkedin.com/in/renee-bartos
